#!/usr/bin/env bash
# Bash script to configure Ubuntu server
# change localhost to 127.0.0.2
# change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1	localhost/127.0.0.2	localhost/' ~/hosts.new
if grep -q 'facebook.com' ~/hosts.new; then
	sed '/s/157.240.11.35	facebook.com/8.8.8.8	facebook.com' ~/hosts.new
else
	sed -i '$a\'"8.8.8.8	facebook.com" ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
